name: "data_product_demo"
version: "1.0.0"
profile: "data_product_demo"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  staging:
    +schema: STAGING
    +materialized: view
  marts:
    +schema: ANALYTICS
    +materialized: table

seeds:
  data_product_demo:
    +schema: RAW
