import streamlit as st
from snowflake.snowpark.context import get_active_session

# ---------------------------------------------------------
# Page Config
# ---------------------------------------------------------

st.set_page_config(
    page_title="Data Product Demo",
    page_icon="📊",
    layout="wide"
)

# ---------------------------------------------------------
# Header
# ---------------------------------------------------------

st.title("📊 Data Product Demo")
st.caption("Snowflake • dbt • Streamlit")

st.markdown(
"""
This is a **demo data product application** running inside Snowflake Streamlit.

It will eventually visualize curated data produced by **dbt models**
from the **ANALYTICS** schema.
"""
)

# ---------------------------------------------------------
# Get Snowflake Session
# (Works inside Snowflake Streamlit)
# ---------------------------------------------------------

session = get_active_session()

# ---------------------------------------------------------
# Demo Query
# ---------------------------------------------------------

st.subheader("System Information")

query = """
SELECT
    CURRENT_ACCOUNT()  AS ACCOUNT,
    CURRENT_USER()     AS USER,
    CURRENT_ROLE()     AS ROLE,
    CURRENT_DATABASE() AS DATABASE,
    CURRENT_SCHEMA()   AS SCHEMA
"""

df = session.sql(query).to_pandas()

st.dataframe(df, use_container_width=True)

# ---------------------------------------------------------
# Future Section Placeholder
# ---------------------------------------------------------

st.subheader("📈 Data Product Dashboard")

st.info(
"""
This section will display curated analytics tables
generated by **dbt models**.

Planned demo components:

- KPI dashboard
- Trend charts
- Aggregated business metrics
- Filterable data views
"""
)

# ---------------------------------------------------------
# Footer
# ---------------------------------------------------------

st.divider()

st.caption(
"""
Demo Architecture:

Terraform → Snowflake → dbt → Streamlit  
All components deployed from a single repository.
"""
)